#!/usr/bin/zsh

# dotfiles
# 
# echo ".cfg" >> .gitignore
# git clone --bare https://github.com/mateuszgrzyb/dotfiles.git $HOME/.dotfiles
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'
# dotfiles checkout
# dotfiles config --local status.showUntrackedFiles no

# safe versions
alias mv='mv -i'
alias rm='rm -i'

# colors

alias ls='ls --color=auto'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# nice ls

alias ll='ls -alF'
alias la='ls -A --ignore=.directory'
alias l='ls -CF'

#alias ls='command ls -F --color=auto'
#alias lsa='command ls -Fa --color=auto'
#alias lsl='command ls -Flh --color=auto'
#alias lsla='command ls -Flah --color=auto'

# edit zsh config

alias zshedit='$EDITOR $HOME/.zshrc'

# reload zsh config

alias zshreload='source $HOME/.zshrc'

# open all files in current directory in neovim

alias avim='nvim -p $(command ls)' 

# Use lf to switch directories

lf () {
    tmp="$(mktemp)"
    command lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] \
        && cd "$dir"
    fi
}
